### ISSUE TITLE
what about

### ISSUE THREAD

**Issue by Kepro** [aweijnitz/pi_backup#1]
service apache2 stop
service mysql stop
service cron stop
service minidlna stop
service samba stop

and default mount point of raspbian is /mnt/usb0
? :))

**Comment by thibmaek** [comment]
This really depends on your setup.
According to the packages someone has installed the list of services to start or stop could be endless.

Configure them yourself, much easier.

**Comment by aweijnitz** [comment]
Following a merge of a pul request, it is now much easier to do the configuration. Checkout the start/stopServices functions at the script.
